version: '2'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./storage/build/scripts/php-fpm
    image: audithsoftworks/php-fpm
    volumes:
      - .:/var/www
    working_dir: /var/www
    environment:
      XDEBUG_CONFIG: "remote_host=172.18.0.1"
      REDIS_PORT: 6379
  nginx:
    container_name: nginx
    build:
      context: ./storage/build/scripts/nginx
    image: audithsoftworks/nginx
    volumes:
      - ./storage/build/configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    working_dir: /var/www
    links:
      - php-fpm:phpFpm
    networks:
      default:
        aliases:
          - basis.audith.org
  dev:
    container_name: dev
    build:
      context: ./storage/build/scripts/php
    image: audithsoftworks/php
    volumes:
      - .:/var/www
      - ./storage/build/configs/crontabs:/var/spool/cron/crontabs
    working_dir: /var/www
    links:
      - nginx
    environment:
      XDEBUG_CONFIG: "remote_host=172.18.0.1"
      REDIS_PORT: 6379
      WORKDIR: "/var/www"
    stdin_open: true
    tty: true
